- name: Non-root user can ssh connect
  hosts: folding
  user: dubovsky
  become: yes
  vars:
    uname: dubovsky
  tasks:

    - name: upgrade all packages
      dnf: name='*' state=latest

    - name: create new user
      user:
        name: "{{ uname }}"
        shell: /bin/bash
        expires: -1
        password: "!"
        create_home: yes

    - name: install packages
      dnf:
        name:
          - sudo
          - openssh
          - curl
          - fuse
          - fuse-libs
        state: latest

    - name: passwordless sudo for user
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^{{ uname }}"
        line: "{{ uname }} ALL=(ALL) ALL"
        validate: 'visudo -cf %s'

    - name: start and enable sshd
      systemd:
        name: sshd
        state: started
        enabled: yes

    - name: upload authorized keys
      authorized_key:
        user: "{{ uname }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/folding.pub') }}"

